# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Maven Package

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
env:
  IMAGE_NAME: ${{ vars.DOCKERHUB_USERNAME }}/vehicle-app
  TAG_NAME: latest
  DOCKER_IMAGE_NAME: test

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/maven_build

      - uses: ./.github/actions/docker_build
        with:
          path_dockerfile: src/main/docker/Dockerfile.jvm
          image_name: ${{ env.IMAGE_NAME }}
          tag_name: ${{ env.TAG_NAME }}

      - uses: ./.github/actions/docker_push
        with:
          DOCKERHUB_USERNAME: ${{ vars.DOCKERHUB_USERNAME }}
          DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}